// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF_XJ-DKS7CQcfgRb-LpIRbknDidB8NPI',
    appId: '1:478496606462:web:7b2c9c6e521f4694483daf',
    messagingSenderId: '478496606462',
    projectId: 'campushealth-fde29',
    authDomain: 'campushealth-fde29.firebaseapp.com',
    storageBucket: 'campushealth-fde29.firebasestorage.app',
    measurementId: 'G-WTS11NEC0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNZvJEs0pVkrCIRfGSgSbKm2eAScaE_Q0',
    appId: '1:478496606462:android:076abf68b09d565b483daf',
    messagingSenderId: '478496606462',
    projectId: 'campushealth-fde29',
    storageBucket: 'campushealth-fde29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCym9bj7bUYo3tsjSCoERgaGMmgg-vfFA0',
    appId: '1:478496606462:ios:955ee23702bc1b69483daf',
    messagingSenderId: '478496606462',
    projectId: 'campushealth-fde29',
    storageBucket: 'campushealth-fde29.firebasestorage.app',
    iosBundleId: 'com.example.campusHealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCym9bj7bUYo3tsjSCoERgaGMmgg-vfFA0',
    appId: '1:478496606462:ios:955ee23702bc1b69483daf',
    messagingSenderId: '478496606462',
    projectId: 'campushealth-fde29',
    storageBucket: 'campushealth-fde29.firebasestorage.app',
    iosBundleId: 'com.example.campusHealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF_XJ-DKS7CQcfgRb-LpIRbknDidB8NPI',
    appId: '1:478496606462:web:8eb1b98f4d57a45d483daf',
    messagingSenderId: '478496606462',
    projectId: 'campushealth-fde29',
    authDomain: 'campushealth-fde29.firebaseapp.com',
    storageBucket: 'campushealth-fde29.firebasestorage.app',
    measurementId: 'G-M7BR9BV5YV',
  );
}
